apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - {{ .Values.app.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.app.pvc.storage }}
  storageClassName: standard-rwo
