apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.app.service.type }}
  ports:
  - name: dgr-http
    protocol: TCP
    port: 80
    targetPort: {{ .Values.app.port.dgr }}
  selector:
    app: {{ .Release.Name }}-app