app:
  replicaCount: 1
  image:
    dgr: 
      repo: null
      tag: null
    composer: 
      repo: null
      tag: null
  file:
    sh: "https://raw.githubusercontent.com/butterpigpig001/digiRunner/refs/heads/main/resources/__call_update_ip_api.sh" 
  service:
    type: LoadBalancer # NodePort
    port: 80
  persistentVolumeClaim:
    storageClass: null
    size: null
  port:
    dgr: 8442
    composer: 8440
